# Lecture 11

For the next few lectures, we are going to work on a basic data analysis problem: grading a class. We will first use pandas to compute grades. Then we will build a grading book system.

## Data Analysis (scripting/notebook)

### Data Preperation

We'll use pandas to read in some grade data. The file we are reading is a CSV dump of a Google Sheet from a TA grading a course. As we soon will see, the file is not properly formatted, and as often is the case, we will have to do a bit of manipulation before the data is usably in memory.

In [2]:
import pandas as pd

In [8]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.

Before we read in the file, lets take a look.

In [4]:
!cat Data-1401-Grades.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

## Data Manipulation with Command-line Tools and Pandas

The file is the CSV export of a google sheet, which isn't ideally formatted:
* First line is the grading rubric, not the column names.
* Lines alternate between the grade and the comments for the specific lab/exam.
* The exam grades are in the format XX-sent.

Reading the file with a CSV reader therefore isn't going to get table in the right format:

In [5]:
df = pd.read_csv("Data-1401-Grades.csv")

In [6]:
df

,"No attempt: -5,wrong:-1...-5","No attempt: -5, wrong: -2","No attempt: -10, wrong: -1..-7","No attempt: -10, wrong: -1 ..-8. no bonus","No attempt: -25, wrong: -1..-20","No attempt: -14, wrong: -1..-12, bonus 0..14","No attempt: -15, wrong: -1..-12, bonus 0..5","No attempt: -14, wrong: -1..-12",Unnamed: 8
0,Lab 1,Lab 2,Lab 3,Lab 4,Exam 1,Lab 5,NaN,Lab 7,Exam 2
1,NaN,0,0,NaN,0,0,0.0,0,0
2,no solution,no solution,-did not submit the Lab,NaN,did not submit the exam,NaN,NaN,NaN,NaN
3,100,96,46,NaN,68-sent,NaN,NaN,NaN,NaN
4,Completed the lab,"ex4- attempted,wrong solution -2\nex8 -wrong s...",ex1 - Nameerror get_size() is not defined(-2)\...,NaN,q1c - does not return the list instead returns...,NaN,NaN,NaN,NaN
5,100,100,90,NaN,88-sent,NaN,NaN,NaN,NaN
6,Completed the lab,Completed the whole lab\n,ex10 - not attempted (-10)\nex11 - not attempted,ex8-not attempted\nex9- not attempted,note - try to use better variable names\nq3b -...,NaN,NaN,NaN,NaN
7,93,100,24,NaN,96-sent,NaN,NaN,NaN,NaN
8,"ex4 - attempted, wrong answer(-2)\nex5c - not ...",Completed the whole lab,"ex2 - returns 1 for winner_2, returns 1 for no...",NaN,note- try not to use names which are built-in ...,NaN,NaN,NaN,NaN
9,0,81,0,0,43-sent,NaN,NaN,NaN,NaN
10,no solution,ex2-attempted(empty list) -2\nex3 - no solutio...,- did not submit the lab,-did not submit the lab,q1b - returns the index 0 instead of 23 as men...,NaN,NaN,NaN,NaN
11,95,100,105,NaN,96-sent,NaN,NaN,NaN,NaN
12,-ex5c missing(-5),Completed the whole lab,ex5 - does not draw board (-5)\nex11 - +10,NaN,"q4b - Implementation correct , gives NameError...",NaN,NaN,NaN,NaN
13,100,98,87,NaN,89-sent,NaN,NaN,NaN,NaN
14,completed the lab,"ex10 - attempted, solution wrong(nameerror-gue...",ex2 - flips for condition 'also_no_winner' ret...,NaN,q3a - did not print the result(-2)\nq3b- solut...,NaN,NaN,NaN,NaN
15,95,98,50,NaN,52,NaN,NaN,NaN,NaN
16,-ex5c missing(-5),"ex8 - wrong solution, sequence should be 1,1,....","ex1 - works for only 1 condition, does not ret...",NaN,"q1a,q1b,q1c - incomplete function. Does not ha...",NaN,NaN,NaN,NaN
17,95,96,98,NaN,100-sent,NaN,NaN,NaN,NaN
18,-ex5c missing(-5),ex8 - should start from 1 as given in the ques...,ex5 - does not return True or False(-2)\nex11 ...,NaN,excellent,NaN,NaN,NaN,NaN
19,0,78,37,NaN,67,NaN,NaN,NaN,NaN
20,no solution,ex1 - 1 function(odd) missing -2\nex2 - no sol...,"ex1 - Nameerror ""game_board"" not defined (-2)\...",NaN,-Late submission -10\nq1b - Nameerror (-3)\nq...,NaN,NaN,NaN,NaN
21,0,76,NaN,NaN,0,NaN,NaN,NaN,NaN
22,no solution,ex1 - syntax error -2\nex3 - wrong solution -2...,NaN,NaN,-did not submit the exam,NaN,NaN,NaN,NaN
23,95,89,0,0,66-sent,NaN,NaN,NaN,NaN
24,ex 5c missing(-5),ex7 - condition not working on rock and scisso...,-did not submit the Lab,-did not submit the Lab,q2- should not be using numpy(built in functio...,NaN,NaN,NaN,NaN
25,98,94,35,NaN,96-sent,NaN,NaN,NaN,NaN
26,ex 4 attempted but not correct(-2),ex3 - wrong solution(attempted) -2\nex4 - wron...,"ex2 - does not return -1, 0, 1, or 2 , return...",NaN,"q2- Right logic but not commented well, commen...",NaN,NaN,NaN,NaN
27,93,77,23,NaN,64-sent,NaN,NaN,NaN,NaN
28,"ex3 attempted no solution, 5c missing(-7)",ex3 - should have taken list of numbers as in ...,"ex2 - returns 1 instead of 0 for ""no_winner"" (...",ex7 -not attempted\nex8- not attempted\nex9- n...,"q1a - You had to return just the string ""Alaba...",NaN,NaN,NaN,NaN
29,100,96,88,NaN,64-sent,NaN,NaN,NaN,NaN
30,completed,ex8 - Sequence should have started from 1 as g...,ex5 - does not return True or False(-2)\nex9 -...,NaN,"q1a - return just the string, not in list form...",NaN,NaN,NaN,NaN
31,95,94,60,NaN,98-sent,NaN,NaN,NaN,NaN
32,ex 5c missing(-5),ex3 - incomplete function -3\nex10 - incomplet...,ex7- not attempted\nex8- not attempted\nex9- n...,NaN,q4b - pair() is not working properly for few t...,NaN,NaN,NaN,NaN

Let's start fixing these issues. First we can just drop the first line. There are lots of ways of doing so... easiest would be to use some of the command line unix utilities we became familiar with in the beginning of the course. First, let's count the lines:

In [7]:
!wc -l Data-1401-grades.csv

'wc' is not recognized as an internal or external command,
operable program or batch file.

We can use the unix command `tail` to write out the lasn n lines of a file... let's use it to drop the first line:

In [9]:
!tail -179 Data-1401-Grades.csv

'tail' is not recognized as an internal or external command,
operable program or batch file.

We can use unix redirection to write the output into another file:

In [10]:
!tail -179 Data-1401-Grades.csv > Data-1401-Grades-Fixed.csv

'tail' is not recognized as an internal or external command,
operable program or batch file.

Let's see the result:

In [11]:
!cat Data-1401-Grades-Fixed.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

Let's Try reading the new file now:

In [12]:
df = pd.read_csv("Data-1401-Grades-Fixed.csv")

EmptyDataError: No columns to parse from file

In [13]:
df

,"No attempt: -5,wrong:-1...-5","No attempt: -5, wrong: -2","No attempt: -10, wrong: -1..-7","No attempt: -10, wrong: -1 ..-8. no bonus","No attempt: -25, wrong: -1..-20","No attempt: -14, wrong: -1..-12, bonus 0..14","No attempt: -15, wrong: -1..-12, bonus 0..5","No attempt: -14, wrong: -1..-12",Unnamed: 8
0,Lab 1,Lab 2,Lab 3,Lab 4,Exam 1,Lab 5,NaN,Lab 7,Exam 2
1,NaN,0,0,NaN,0,0,0.0,0,0
2,no solution,no solution,-did not submit the Lab,NaN,did not submit the exam,NaN,NaN,NaN,NaN
3,100,96,46,NaN,68-sent,NaN,NaN,NaN,NaN
4,Completed the lab,"ex4- attempted,wrong solution -2\nex8 -wrong s...",ex1 - Nameerror get_size() is not defined(-2)\...,NaN,q1c - does not return the list instead returns...,NaN,NaN,NaN,NaN
5,100,100,90,NaN,88-sent,NaN,NaN,NaN,NaN
6,Completed the lab,Completed the whole lab\n,ex10 - not attempted (-10)\nex11 - not attempted,ex8-not attempted\nex9- not attempted,note - try to use better variable names\nq3b -...,NaN,NaN,NaN,NaN
7,93,100,24,NaN,96-sent,NaN,NaN,NaN,NaN
8,"ex4 - attempted, wrong answer(-2)\nex5c - not ...",Completed the whole lab,"ex2 - returns 1 for winner_2, returns 1 for no...",NaN,note- try not to use names which are built-in ...,NaN,NaN,NaN,NaN
9,0,81,0,0,43-sent,NaN,NaN,NaN,NaN
10,no solution,ex2-attempted(empty list) -2\nex3 - no solutio...,- did not submit the lab,-did not submit the lab,q1b - returns the index 0 instead of 23 as men...,NaN,NaN,NaN,NaN
11,95,100,105,NaN,96-sent,NaN,NaN,NaN,NaN
12,-ex5c missing(-5),Completed the whole lab,ex5 - does not draw board (-5)\nex11 - +10,NaN,"q4b - Implementation correct , gives NameError...",NaN,NaN,NaN,NaN
13,100,98,87,NaN,89-sent,NaN,NaN,NaN,NaN
14,completed the lab,"ex10 - attempted, solution wrong(nameerror-gue...",ex2 - flips for condition 'also_no_winner' ret...,NaN,q3a - did not print the result(-2)\nq3b- solut...,NaN,NaN,NaN,NaN
15,95,98,50,NaN,52,NaN,NaN,NaN,NaN
16,-ex5c missing(-5),"ex8 - wrong solution, sequence should be 1,1,....","ex1 - works for only 1 condition, does not ret...",NaN,"q1a,q1b,q1c - incomplete function. Does not ha...",NaN,NaN,NaN,NaN
17,95,96,98,NaN,100-sent,NaN,NaN,NaN,NaN
18,-ex5c missing(-5),ex8 - should start from 1 as given in the ques...,ex5 - does not return True or False(-2)\nex11 ...,NaN,excellent,NaN,NaN,NaN,NaN
19,0,78,37,NaN,67,NaN,NaN,NaN,NaN
20,no solution,ex1 - 1 function(odd) missing -2\nex2 - no sol...,"ex1 - Nameerror ""game_board"" not defined (-2)\...",NaN,-Late submission -10\nq1b - Nameerror (-3)\nq...,NaN,NaN,NaN,NaN
21,0,76,NaN,NaN,0,NaN,NaN,NaN,NaN
22,no solution,ex1 - syntax error -2\nex3 - wrong solution -2...,NaN,NaN,-did not submit the exam,NaN,NaN,NaN,NaN
23,95,89,0,0,66-sent,NaN,NaN,NaN,NaN
24,ex 5c missing(-5),ex7 - condition not working on rock and scisso...,-did not submit the Lab,-did not submit the Lab,q2- should not be using numpy(built in functio...,NaN,NaN,NaN,NaN
25,98,94,35,NaN,96-sent,NaN,NaN,NaN,NaN
26,ex 4 attempted but not correct(-2),ex3 - wrong solution(attempted) -2\nex4 - wron...,"ex2 - does not return -1, 0, 1, or 2 , return...",NaN,"q2- Right logic but not commented well, commen...",NaN,NaN,NaN,NaN
27,93,77,23,NaN,64-sent,NaN,NaN,NaN,NaN
28,"ex3 attempted no solution, 5c missing(-7)",ex3 - should have taken list of numbers as in ...,"ex2 - returns 1 instead of 0 for ""no_winner"" (...",ex7 -not attempted\nex8- not attempted\nex9- n...,"q1a - You had to return just the string ""Alaba...",NaN,NaN,NaN,NaN
29,100,96,88,NaN,64-sent,NaN,NaN,NaN,NaN
30,completed,ex8 - Sequence should have started from 1 as g...,ex5 - does not return True or False(-2)\nex9 -...,NaN,"q1a - return just the string, not in list form...",NaN,NaN,NaN,NaN
31,95,94,60,NaN,98-sent,NaN,NaN,NaN,NaN
32,ex 5c missing(-5),ex3 - incomplete function -3\nex10 - incomplet...,ex7- not attempted\nex8- not attempted\nex9- n...,NaN,q4b - pair() is not working properly for few t...,NaN,NaN,NaN,NaN

Now we have to deal with the problem that every other line contains information we don't need. For example:

In [14]:
df["Lab 1"]

KeyError: 'Lab 1'

The data is now in memory stored as a data frame. Let's take a few minutes and go over the features of DataFrame from the Pandas documentation:

* [Pandas Data Structures](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dsintro)
* [Pandas DataFrame in 10 minutes](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html)

We can deal with the 'every-other-line" problem by using Pandas to create a new DataFrame from select row of our existing DataFrame using Boolean indexing. Basically, if you use index a DataFrame with a list of booleans with the same length as the number of rows in the DataFrame, it'll use the booleans to select the rows. So we need a list containing of laternating True/False booleans:

In [15]:
mask = list()
for i in range(16):
	mask.append(True)
	mask.append(False)
mask

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [16]:
df_0 = df[mask]

ValueError: Item wrong length 32 instead of 33.

In [17]:
df_0

NameError: name 'df_0' is not defined

Next, we have to fix the "Exam 1" column and remove "-sent" from it. Here's the plan:

* Ask DataFrame for the column
* Convert Column into a list.
* Fix Every item of the list
	* Remove "-sent"
	* Convert to int (from string)
* Add back the fixed list as a new column.

In [19]:
# 1
df_0["Exam 1"]

NameError: name 'df_0' is not defined

In [20]:
# 2
df_0["Exam 1"].tolist()

NameError: name 'df_0' is not defined

In [21]:
#3A
list(map(lambda x: x.split("-")[0], df_0["Exam 1"].tolist()))

NameError: name 'df_0' is not defined

In [22]:
# 3B
list(map(lambda x: int(x.split("-")[0]), df_0["Exam 1"].tolist()))

NameError: name 'df_0' is not defined

In [ ]:
# 4
df_0["Exam 1 Fixed"] = list(map(lambda x: int(x.split("-")[0]), df_0["Exam 1"].tolist()))

In [23]:
df_0

NameError: name 'df_0' is not defined

We finally have the exam data in a `DataFrame` in a way we can use it:

In [24]:
df_0

NameError: name 'df_0' is not defined

## Data Visualization / Analysis

First thing, make a histogram:

In [27]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(df_0["exam 1 Fixed"], bins = 40)

NameError: name 'df_0' is not defined

In [28]:
df_0["Exam 1 Fixed"]

NameError: name 'df_0' is not defined

In [ ]:
import numpy as np
print("Mean:", np.mean(df_0["Exam 1 Fixed"]))